### ISSUE TITLE
Parsing the current document in custom tags

### ISSUE THREAD

**Issue by bpaugam** [shiwano/grunt-yaml#13]
Can I have a self-document-referencing custom tag ?

For example:

``` yaml
# theme.yml
palettes:
  grey:
    color: '#666'
    text: '#FFF'

body:
  color: !palette
    name: grey
    property: color
```

``` js
customTypes: {
    '!palette mapping': function(values) {
        var yamlFile = someHowMagicallyRetrieveTheWholeDocumentAsAnObject;
        return yamlFile.palettes[values.color][values.property];
    },
},
```

Json output:

``` json
{
  "palettes": {
    "grey": {
      "color": "#666",
      "text": "#FFF",
    }
  },
  "body": {
    "color": "#666"
  }
}
```
